# Generated by Django 5.1.7 on 2025-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Post title")),
                (
                    "excerpt",
                    models.CharField(max_length=250, verbose_name="Post excerpt"),
                ),
                ("body", models.TextField(blank=True, verbose_name="Post body")),
                ("published_at", models.DateField(verbose_name="Post published at")),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
