# Generated by Django 5.1.7 on 2025-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Post title")),
                (
                    "excerpt",
                    models.CharField(max_length=250, verbose_name="Post excerpt"),
                ),
                ("body", models.TextField(blank=True, verbose_name="Post body")),
                (
                    "published_at",
                    models.DateTimeField(verbose_name="Post published at"),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.DeleteModel(
            name="Articles",
        ),
    ]
